{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "travel-together-grafana.fullname" .) .Values.serviceAccount.name }}
  labels:
    app: {{ include "travel-together-grafana.name" . }}
{{- end }}
