apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel-together-grafana.fullname" . }}
  labels:
    app: {{ include "travel-together-grafana.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "travel-together-grafana.name" . }}
